export const siteData = {
  name: 'Jevvi Supratama',
  firstName: 'JEVVI',
  initials: 'J',
  title: 'Software Developer & IT Professional',
  email: 'jevvisupratama@gmail.com',
  github: 'github.com/jevvisupratama',
  githubUrl: 'https://github.com/jevvisupratama',
  linkedin: 'linkedin.com/in/jevvi-supratama',
  linkedinUrl: 'https://linkedin.com/in/jevvi-supratama',
  resumeUrl: '/resume.pdf',
  heroName: 'JEVVI SUPRATAMA',
  about: {
    description: "I'm open to opportunities where I can contribute to software testing, web development, IT operations, and digital workflows.",
    tagline: 'Looking for the next problem worth solving.',
  },
  navLinks: [
    { label: 'Work', href: '#work' },
    { label: 'What I Can Do', href: '#skills' },
    { label: 'About', href: '#about' },
    { label: 'Awards', href: '#awards' },
    { label: 'Trainings', href: '#trainings' },
  ],
  selectedWork: [
    {
      id: 1,
      title: 'Boarding House Rental System',
      description: 'Developed a web-based boarding house rental platform for managing property listings, bookings, payments, and reviews, with separate access and features for students, landlords, and administrators.',
      image: '/projects/boarding-house.jpg',
      link: '#',
    },
    {
      id: 2,
      title: 'RFID-Based CPSC Student Monitoring System with Automated Photo Capture and Email Notification',
      description: 'Developed an RFID-based student monitoring system that automates attendance tracking through RFID scanning, photo capture, email notifications, Google Drive export, and administrative reporting. Awarded Best Capstone Paper and Best Capstone System.',
      image: '/projects/rfid-system.jpg',
      link: '#',
    },
    {
      id: 3,
      title: 'DocuTrack Document Tracking System',
      description: 'A comprehensive document tracking and management system for efficient file organization and workflow.',
      image: '/projects/docutrack.jpg',
      link: '#',
    },
    {
      id: 4,
      title: 'Empowering Rapid Development',
      description: 'A platform designed to accelerate development workflows and team productivity.',
      image: '/projects/empowering.jpg',
      link: '#',
    },
  ],
  technicalProjects: [
    {
      number: '01',
      title: 'ITrak Terminal Management System',
      description: 'Web-based system for tracking and managing terminal operations, schedules, and reporting.',
      framework: 'CodeIgniter 4',
      techStack: ['HTML', 'CSS', 'JavaScript', 'PHP', 'Bootstrap', 'MySQL'],
      link: 'https://github.com/chardoxx-3/ITrak-Terminal-Management-System',
    },
    {
      number: '02',
      title: 'LGU Financial Management System',
      description: 'Web-based financial management system for local government units handling budget allocation, expenditure tracking, and financial reporting.',
      framework: 'CodeIgniter 4',
      techStack: ['HTML', 'CSS', 'JavaScript', 'PHP', 'Bootstrap', 'MySQL'],
      link: '#',
    },
    {
      number: '03',
      title: 'Scholarship Management System',
      description: 'Web-based system for managing scholarship applications, approvals, disbursements, and scholar records.',
      framework: 'CodeIgniter 4',
      techStack: ['HTML', 'CSS', 'JavaScript', 'PHP', 'Bootstrap', 'MySQL'],
      link: '#',
    },
    {
      number: '04',
      title: 'Tourism Management System',
      description: 'Web-based tourism management platform for destination listings, bookings, and tourist information services.',
      framework: 'CodeIgniter 4',
      techStack: ['HTML', 'CSS', 'JavaScript', 'PHP', 'Bootstrap', 'MySQL'],
      link: '#',
    },
    {
      number: '05',
      title: 'Boarding House Rental System',
      description: 'Web-based boarding house rental platform for managing property listings, bookings, payments, and reviews with separate access for students, landlords, and administrators.',
      framework: 'CodeIgniter 4',
      techStack: ['HTML', 'CSS', 'JavaScript', 'PHP', 'Bootstrap', 'MySQL'],
      link: '#',
    },
    {
      number: '06',
      title: 'PayTrack - Employee Payroll Management System',
      description: 'PHP-based payroll management system for handling employee compensation, deductions, and payroll processing with centralized record management.',
      framework: 'CodeIgniter 4',
      techStack: ['HTML', 'CSS', 'JavaScript', 'PHP', 'Bootstrap', 'MySQL'],
      link: '#',
    },
    {
      number: '07',
      title: 'Barangay Residents Management System',
      description: 'Web-based system for Barangay Benoni, Mahinog, Camiguin, designed to streamline resident records, reservations, payments, and reporting.',
      framework: 'CodeIgniter 4',
      techStack: ['HTML', 'CSS', 'JavaScript', 'PHP', 'Bootstrap', 'MySQL'],
      link: '#',
    },
    {
      number: '08',
      title: 'Sari-Sari Store Utang Management System',
      description: 'Web-based system for managing customer credit accounts, tracking outstanding debts, recording payments, and handling item reservations for a sari-sari store.',
      framework: 'CodeIgniter 4',
      techStack: ['HTML', 'CSS', 'JavaScript', 'PHP', 'Bootstrap', 'MySQL'],
      link: '#',
    },
    {
      number: '09',
      title: 'Employee Management System',
      description: 'Web-based system for managing employee records, attendance tracking, payroll processing, and employee requests in one platform.',
      framework: 'CodeIgniter 4',
      techStack: ['HTML', 'CSS', 'JavaScript', 'PHP', 'Bootstrap', 'MySQL'],
      link: '#',
    },
    {
      number: '10',
      title: 'Inventory Management System',
      description: 'Web-based inventory tracking and management system for stock monitoring, order processing, and supply chain management.',
      framework: 'CodeIgniter 4',
      techStack: ['HTML', 'CSS', 'JavaScript', 'PHP', 'Bootstrap', 'MySQL'],
      link: '#',
    },
    {
      number: '11',
      title: 'Library Management System',
      description: 'Web-based system for managing library resources, book borrowing, returns, and member records.',
      framework: 'CodeIgniter 4',
      techStack: ['HTML', 'CSS', 'JavaScript', 'PHP', 'Bootstrap', 'MySQL'],
      link: '#',
    },
    {
      number: '12',
      title: 'Student Information System',
      description: 'Web-based platform for managing student enrollment, grades, class schedules, and academic records.',
      framework: 'CodeIgniter 4',
      techStack: ['HTML', 'CSS', 'JavaScript', 'PHP', 'Bootstrap', 'MySQL'],
      link: '#',
    },
    {
      number: '13',
      title: 'POS System',
      description: 'Web-based point of sale system for retail operations, transaction processing, and sales reporting.',
      framework: 'CodeIgniter 4',
      techStack: ['HTML', 'CSS', 'JavaScript', 'PHP', 'Bootstrap', 'MySQL'],
      link: '#',
    },
    {
      number: '14',
      title: 'Hotel Reservation System',
      description: 'Web-based hotel booking and management platform for room reservations, guest management, and billing.',
      framework: 'CodeIgniter 4',
      techStack: ['HTML', 'CSS', 'JavaScript', 'PHP', 'Bootstrap', 'MySQL'],
      link: '#',
    },
    {
      number: '15',
      title: 'E-Commerce Platform',
      description: 'Web-based shopping platform with product catalog, cart, checkout, and order management features.',
      framework: 'CodeIgniter 4',
      techStack: ['HTML', 'CSS', 'JavaScript', 'PHP', 'Bootstrap', 'MySQL'],
      link: '#',
    },
    {
      number: '16',
      title: 'Event Management System',
      description: 'Web-based platform for organizing events, managing registrations, and coordinating schedules.',
      framework: 'CodeIgniter 4',
      techStack: ['HTML', 'CSS', 'JavaScript', 'PHP', 'Bootstrap', 'MySQL'],
      link: '#',
    },
    {
      number: '17',
      title: 'Clinic Management System',
      description: 'Web-based clinic management platform for patient records, appointment scheduling, and medical history tracking.',
      framework: 'CodeIgniter 4',
      techStack: ['HTML', 'CSS', 'JavaScript', 'PHP', 'Bootstrap', 'MySQL'],
      link: '#',
    },
    {
      number: '18',
      title: 'Real Estate Management System',
      description: 'Web-based real estate platform for property listings, agent management, and client inquiries.',
      framework: 'CodeIgniter 4',
      techStack: ['HTML', 'CSS', 'JavaScript', 'PHP', 'Bootstrap', 'MySQL'],
      link: '#',
    },
    {
      number: '19',
      title: 'Gym Management System',
      description: 'Web-based gym management platform for managing memberships, attendance, payments, class schedules, and general gym operations.',
      framework: 'CodeIgniter 4',
      techStack: ['HTML', 'CSS', 'JavaScript', 'PHP', 'Bootstrap', 'MySQL'],
      link: '#',
    },
    {
      number: '20',
      title: 'Car Rental Management System',
      description: 'Web-based car rental platform for vehicle browsing and reservations, including administrative tools for managing cars, customers, payments, and reports.',
      framework: 'CodeIgniter 4',
      techStack: ['HTML', 'CSS', 'JavaScript', 'PHP', 'Bootstrap', 'MySQL'],
      link: '#',
    },
  ],
  digitalProjects: [
    {
      number: '01',
      title: 'Infographic Design Collection',
      description: 'A series of informational graphics designed for educational and promotional purposes.',
      image: '/projects/digital-1.jpg',
    },
    {
      number: '02',
      title: 'Brand Identity Package',
      description: 'Complete brand identity design including logos, color palettes, and brand guidelines.',
      image: '/projects/digital-2.jpg',
    },
    {
      number: '03',
      title: 'UI/UX Design Portfolio',
      description: 'Collection of user interface and user experience designs for various applications.',
      image: '/projects/digital-3.jpg',
    },
    {
      number: '04',
      title: 'Content Planning & Scheduling',
      description: 'A visual content planning system designed to organize social media posts, schedules, and publishing activities for consistent content delivery.',
      image: '/projects/digital-4.jpg',
    },
    {
      number: '05',
      title: 'Social Media Content Kit',
      description: 'A collection of social media templates, graphics, and caption frameworks designed to maintain consistent and engaging brand content.',
      image: '/projects/digital-5.jpg',
    },
  ],
  skills: [
    { title: 'Web Development', description: 'Full-stack web applications using modern frameworks and technologies.' },
    { title: 'Software Testing', description: 'Manual and automated testing, QA processes, and bug tracking.' },
    { title: 'IT Operations', description: 'System administration, network management, and technical support.' },
    { title: 'Digital Workflows', description: 'Process automation, content management, and digital transformation.' },
    { title: 'UI/UX Design', description: 'User interface design, prototyping, and user experience optimization.' },
    { title: 'Content Creation', description: 'Digital content, graphics, and social media management.' },
  ],
  awards: [
    { title: 'Best Capstone Paper', event: 'CPSC Capstone Presentation', year: '2024' },
    { title: 'Best Capstone System', event: 'CPSC Capstone Presentation', year: '2024' },
  ],
  trainings: [
    { title: 'Web Development Bootcamp', provider: 'Online Course', year: '2023' },
    { title: 'Software Testing Fundamentals', provider: 'Professional Training', year: '2023' },
    { title: 'IT Operations Certification', provider: 'Technical Institute', year: '2024' },
  ],
}
